sudo: false
addons:
  apt:
    packages:
      - ikiwiki
      - libtext-multimarkdown-perl
      - libimage-magick-perl
      - git
      - texlive-latex-base
      - texlive-latex-extra
      - pgf
script:
  - html=$(mktemp -d)
  - ikiwiki --plugin goodstuff --rebuild --verbose . $html
  - rm -rf $html
  - ./bin/restore-timestamp-git-commit corporate/annual-reports
  - cd corporate/annual-reports
  - touch *.tex
  - make all
  - cd ../..
