on:
  - push
  - pull_request
jobs:
  test:
    name: Web site
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install ikiwiki libtext-multimarkdown-perl libimage-magick-perl
      - run: mkdir ../html
      - run: rm -f README.md CONTRIBUTING.md  # don't build
      - run: ./bin/build-site . ../html
      - run: pip install html5validator
      - run: html5validator --root ../html
  docs:
    name: Annual reports
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: corporate/annual-reports
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install texlive-latex-base texlive-latex-extra texlive-fonts-recommended
      - run: rm *.pdf
      - run: make all
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: find -name "*.yaml" -exec yamllint -s {} \;
